version: '3.8'

services:
  app:
    image: oven/bun:1.0-alpine
    restart: always
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGODB_URI=${MONGODB_URI}
      - DBPASSWORD=${DBPASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
    command: bun src/server.ts
