services:
  xunback:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      PORT: "${PORT}"
      MONGODB_URI: "${MONGODB_URI}"
      DBPASSWORD: '${DBPASSWORD}'
      FRONTEND_URL: '${FRONTEND_URL}'
    networks:
      - alice

networks:
  alice: {}
